name: Publish to NPM
on:
  release:
    types: [created]
env:
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm install pnpm@latest -g
      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: Install dependencies and build 🔧
        run: pnpm install --frozen-lockfile=false && pnpm run build
      - name: Publish package on NPM 📦
        run: pnpm run publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
